### ISSUE TITLE
Xiaomi Redmi 4X boot logos not properly being unpacked

### ISSUE THREAD

**Issue by matu6968** [m-obeid/ximi_logo_dmp#1]
When you try to extract it's images from a Xiaomi Redmi 4X splash.img file, for some reason, it pulls it as one whole bitmap image and any picture viewer refuses to show it because of an invalid structure of the bitmap that it gave out. (The polish message translated says "This image format is unsupported")
![The extracted bitmap that it gave out refuses to open](https://user-images.githubusercontent.com/89382946/210433922-3a741aeb-4c0b-4dca-8b21-856acffa7f8d.png)
I also provided the splash.img file from the phone in a GDrive link for research purposes: https://drive.google.com/file/d/1Yx53bfRyuGhEiSGrBYCprBDUnVkijQrH/view?usp=sharing

**Comment by m-obeid** [comment]
After investigation of the provided file, I discovered that the image file of this device seems to be different than what other devices use. It contains all kinds of file formats for some reason, the program only expects bmp only. Is it the Quallcomm model or MediaTek? What firmware version / MIUI are you running?

**Comment by matu6968** [comment]
It is the Snapdragon 430 model of the Redmi, and it has a custom ROM based of Lineage OS 19.1

**Comment by m-obeid** [comment]
Ok so it seems this tool is made for newer versions of the format. the oldest device's logo i have tested it on is the redmi note 5, which seems to work. Im pretty sure theres a tool on xda for your device, good luck.
